import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#3323cc",
        "surface-tint": "#4d44e3",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "surface-dim": "#cbdbf5",
        "outline": "#777587",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed-dim": "#ffb95f",
        "secondary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#ffd4a4",
        "on-surface-variant": "#464555",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed": "#e2dfff",
        "surface": "#f8f9ff",
        "outline-variant": "#c7c4d8",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#4f46e5",
        "inverse-primary": "#c3c0ff",
        "surface-container": "#e5eeff",
        "tertiary-container": "#885500",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-container": "#00714d",
        "tertiary": "#684000",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "on-secondary-fixed": "#002113",
        "secondary-container": "#6cf8bb",
        "background": "#f8f9ff",
        "secondary": "#006c49",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "on-surface": "#0b1c30",
        "secondary-fixed": "#6ffbbe",
        "primary": "#3525cd",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-container": "#dad7ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        base: "4px",
        gutter: "1.5rem",
      },
      maxWidth: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
      },
      fontFamily: {
        "title-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
